name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

template: |
  $CHANGES

  Thanks to all contributors!
  $CONTRIBUTORS

categories:
  - title: 🏆 Highlights
    when:
      labels:
        - highlight
  - title: 💥 Breaking changes
    semver-increment: "major"
    when:
      labels:
        - breaking
  - title: ⚠️ Deprecations
    when:
      labels:
        - deprecation
  - title: 🚀 Performance improvements
    semver-increment: "minor"
    when:
      labels:
        - performance
  - title: ✨ Enhancements
    semver-increment: "minor"
    when:
      labels:
        - enhancement
  - title: 🐞 Bug fixes
    when:
      labels:
        - fix
  - title: 📖 Documentation
    when:
      labels:
        - documentation
  - title: 📦 Build system
    when:
      labels:
        - build
  - title: 🛠️ Other improvements
    when:
      labels:
        - internal
  - type: "pre-exclude"
    when:
      labels:
        - skip changelog
        - release

change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  default: patch

replacers:
  # Remove conventional commits from titles
  - search: '/- (build|chore|ci|depr|docs|feat|fix|perf|refactor|release|test)(\(.*\))?(\!)?\: /g'
    replace: '- '

autolabeler:
  - label: breaking
    title:
      - '/^(build|chore|ci|depr|docs|feat|fix|perf|refactor|release|test)(\(.*\))?\!\: /'
  - label: build
    title:
      - '/^build/'
  - label: internal
    title:
      - '/^(chore|ci|refactor|test)/'
  - label: deprecation
    title:
      - '/^depr/'
  - label: documentation
    title:
      - '/^docs/'
  - label: enhancement
    title:
      - '/^feat/'
  - label: fix
    title:
      - '/^fix/'
  - label: performance
    title:
      - '/^perf/'
  - label: release
    title:
      - '/^release/'
