# paths to ignore
ignore:
  - ".github/**/*"
  - ".pytest_cache/**/*"
  - ".venv/**/*"
  - ".vscode/**/*"
  - "build_tools/**/*"
  - "docs/**/*"
  - "interactive/**/*"
  - "*.md"
  - "*.yml"
  - "*.yaml"
  - "*.cfg"
  - "*/tests/*"
  - "test_*.py"
