name: Update draft releases

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      sha:
        description: Commit SHA. If omitted, the latest commit on the main branch is used.
        type: string

permissions:
  contents: write
  pull-requests: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Draft release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          commitish: ${{ inputs.sha || github.sha }}
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
