name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytests:
    name: pytests (os=${{ matrix.os }}, python=${{ matrix.python-version }}, with-numba=${{ matrix.with-numba }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.14']
        with-numba: [false, true]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create virtual environment
        run: |
          python -m venv .venv
      - name: Add venv to PATH
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            echo "$GITHUB_WORKSPACE/.venv/Scripts" >> $GITHUB_PATH
          else
            echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
          fi
      - name: Install dependencies
        run: |
          pip install uv
          if [ "${{ matrix.with-numba }}" = "true" ]; then
            uv pip install .[numba]
          else
            uv pip install .
          fi
          uv pip install -r requirements-test.txt
      - name: Run tests
        run: |
          python -m pytest --cov --cov-report=xml --cov-report=term
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
