name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytests:
    name: pytests (python=${{ matrix.python-version }}, with-numba=${{ matrix.with-numba }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.13.3']
        with-numba: [false, true]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create virtual environment
        run: |
          python -m venv .venv
      - name: Install dependencies
        run: |
          pip install uv
          if [ "${{ matrix.with-numba }}" = "true" ]; then
            uv pip install .[numba]
          else
            uv pip install .
          fi
          uv pip install -r requirements-test.txt
      - name: Run tests
        run: |
          .venv/bin/python -m pytest --cov --cov-report=xml --cov-report=term
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
